name: glaucus
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy=1.20
  - pip=21
  - pytorch=1.8.1
  - torchvision=0.9.1
  - torchaudio=0.8.1
  - cpuonly
  - spacy-model-en_core_web_sm=3.0.0
  - nltk=3.6.2
  - pip:
    - annoy==1.17.0
    - elasticsearch==7.13.1
    - elasticsearch-dsl==7.3.0
    - gensim==3.8.3
    - hyperloglog==0.0.12
    - pandas==1.2.4
    - regex==2021.4.4
    - spacy==3.0.6
    - tqdm==4.49.0
